//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "course")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub subject: String,
    pub leader: String,
    #[sea_orm(column_type = "Double")]
    pub tuition_cost: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::student::Entity> for Entity {
    fn to() -> RelationDef {
        super::enrolement::Relation::Student.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::enrolement::Relation::Course.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
