//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "student")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub email: String,
    pub student_id: String,
    pub phone_number: Option<String>,
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        super::enrolement::Relation::Course.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::enrolement::Relation::Student.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
